# Generated by Django 4.1.4 on 2022-12-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_telegram_name_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_landlord',
            field=models.BooleanField(default=False, verbose_name='Арендодатель'),
        ),
    ]
