# Generated by Django 4.1.4 on 2022-12-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_client_user_is_landlord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_landlord',
        ),
    ]
