# Generated by Django 4.1.4 on 2023-01-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0003_alter_landlord_abbreviated_name_and_more'),
        ('rent', '0002_remove_rent_landlord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='landlord_id',
            field=models.ManyToManyField(related_name='Rent', to='landlord.landlord'),
        ),
    ]
