# Generated by Django 4.1.4 on 2023-01-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rent_landlord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='landlord_id',
        ),
    ]
