# Generated by Django 4.1.4 on 2022-12-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opening_hours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='адресс')),
                ('entrance_number', models.CharField(max_length=255, verbose_name='№ Входа')),
                ('floor', models.CharField(max_length=255, verbose_name='Этаж')),
                ('table', models.CharField(max_length=255, verbose_name='Стол')),
                ('square', models.CharField(max_length=255, verbose_name='Площадь')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('undeground', models.CharField(max_length=255, verbose_name='Метро')),
                ('photo', models.ImageField(upload_to='users/photos', verbose_name='фото')),
                ('bio', models.TextField(verbose_name='описание рабочего места')),
                ('place', models.ManyToManyField(related_name='Place', to='opening_hours.opening_hours')),
            ],
        ),
    ]
