# Generated by Django 4.1.4 on 2022-12-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='Opening_Hours',
        ),
    ]
