# Generated by Django 4.1.4 on 2022-12-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_email', models.EmailField(max_length=255, unique=True, verbose_name='Email name')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='users/photos', verbose_name='фото')),
                ('bio', models.TextField(verbose_name='о себе')),
                ('work_telegram_name', models.CharField(max_length=255, verbose_name='Телеграмм_логин')),
                ('address', models.TextField(verbose_name='адресс')),
                ('place', models.ManyToManyField(related_name='LandLord', to='place.place')),
            ],
        ),
    ]
