# Generated by Django 4.1.4 on 2022-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='last_name',
            new_name='abbreviated_name',
        ),
        migrations.RenameField(
            model_name='landlord',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='landlord',
            old_name='work_telegram_name',
            new_name='manager_telegram_name',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='photo',
        ),
        migrations.AddField(
            model_name='landlord',
            name='logo',
            field=models.ImageField(default=0, upload_to='users/photos', verbose_name='лого'),
            preserve_default=False,
        ),
    ]
